[phases.setup]
nixPkgs = ["jdk11", "maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["mvn dependency:copy-dependencies"]

[start]
cmd = "java -jar target/dependency/webapp-runner.jar --port $PORT target/File_Handling_and_Duplication-1.0.war"
